version: "3.8"
services:
  frontend-quarkus:
    image: nginx:latest
    restart: always
    container_name: nginx-frt
    ports:
      - "80:80"
    networks:
      ionos_network_frt:
        ipv4_address: 192.168.1.9
          #    volumes:
          #      - nginx_vol:/usr/share/nginx/html
          #
          #volumes:
          #  nginx_vol:
          #    driver: local
          #    driver_opts:
          #      type: none
          #      device: /volumes/nginx_vol
          #      o: bind

networks:
  ionos_network_frt:
    name: ionos_net_frt
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
